version: "3.0"

# this just binds the images so nginx can serve them properly
volumes:
  public-volume:

services:
  shino_maria_db:
    container_name: shino_maria_db
    image: mariadb:10.5.5
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mariadblib:/var/lib/mysql

  shino_php_fpm:
    container_name: shino_php_fpm
    image: ghcr.io/pkly/shinobu-bot/shinobu-config:latest
    restart: unless-stopped
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@shino_maria_db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.5.5
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - public-volume:/var/www/public

  shino_nginx:
    container_name: shino_nginx
    image: ghcr.io/pkly/shinobu-bot/shinobu-nginx:latest
    restart: unless-stopped
    depends_on:
      - shino_php_fpm
    volumes:
      - public-volume:/var/www/public:ro
      - ./logs/nginx:/var/log/nginx
      - ${SSL_PATH}/conf/live/config.shinobu.chat/fullchain.pem:/etc/ssl/fullchain.pem:ro
      - ${SSL_PATH}/conf/live/config.shinobu.chat/privkey.pem:/etc/ssl/privkey.pem:ro
      - ./certbot:/var/www/certbot
    ports:
      - "443:443"
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx'"

  shino_certbot:
    container_name: shino_certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot:/var/www/certbot
      - ${SSL_PATH}/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  shino_bot:
    container_name: shino_bot
    image: ghcr.io/pkly/shinobu-bot/shinobu-bot:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PREFIX=${BOT_PREFIX}
      - EMBED_COLOR=${BOT_COLOR}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - EMOTE_DEAD=${EMOTE_DEAD}
      - EMOTE_LOADING=${EMOTE_LOADING}
      - EMOTE_VERIFIED=${EMOTE_VERIFIED}
      - EMOTE_DANCE=${EMOTE_DANCE}
      - EMOTE_PLUS=${EMOTE_PLUS}
      - EMOTE_MINUS=${EMOTE_MINUS}
      - EMOTE_NEUTRAL=${EMOTE_NEUTRAL}
      - EMOTE_COINFLIP=${EMOTE_COINFLIP}
    volumes:
      - ./logs/bot:/home/bot/logs

  shino_watchtower:
    container_name: shino_watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: shino_php_fpm shino_bot --interval 600