version: "3.0"

# this just binds the images so nginx can serve them properly
volumes:
  public-volume:

services:
  shino_maria_db:
    container_name: shino_maria_db
    build:
      context: ./db
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  shino_php_fpm:
    container_name: shino_php_fpm
    image: docker.pkg.github.com/pkly/shinobu-bot/shinobu-config:latest
    restart: unless-stopped
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@shino_maria_db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.5.5
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - public-volume:/var/www/public

  shino_nginx:
    container_name: shino_nginx
    build:
      context: ./nginx
    depends_on:
      - shino_php_fpm
    volumes:
      - public-volume:/var/www/public:ro
      - ./nginx/prod-nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - "${NGINX_PORT}:443"