version: "3.0"
services:
  shino_maria_db:
    container_name: shino_maria_db
    image: mariadb:10.5.5
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mariadblib:/var/lib/mysql

  shino_php_fpm:
    container_name: shino_php_fpm
    build:
      context: ./php-fpm
    restart: unless-stopped
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@shino_maria_db:3306/${MYSQL_DATABASE}?serverVersion=mariadb-10.5.5
    volumes:
      - ../:/var/www
      - ./php-fpm/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php-fpm/ini/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/conf/php-fpm-custom.conf:/usr/local/etc/php-fpm.d/zz-php-fpm-custom.conf:ro
    dns:
      - 1.1.1.1
      - 1.0.0.1

  shino_nginx:
    container_name: shino_nginx
    build:
      context: ./nginx
    depends_on:
      - shino_php_fpm
    volumes:
      - ../:/var/www
      - ./nginx/dev-nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"