// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shinobu.Database;

namespace Shinobu.Migrations
{
    [DbContext(typeof(ShinobuDbContext))]
    partial class ShinobuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Shinobu.Database.Entity.Command.Block", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Blocked")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Requester")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("c__block");
                });
#pragma warning restore 612, 618
        }
    }
}
