on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build C# binary
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: dotnet build --configuration Release bot/Shinobu.csproj
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Shinobu.dll
          path: bot/bin/Release/net5.0/Shinobu.dll