on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build C# binary
    
    steps:
      - uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: '5.0.x'
      - name: Build
        run: |
          ls ../shinobu-bot -la
          dotnet build --configuration Release ../shinobu-bot/bot/src/Shinobu